[PHP]
extension_dir = "D:\server\frankenphp\ext"

extension=mbstring
extension=openssl
extension=curl
extension=fileinfo
extension=pdo_mysql
extension=mysqli
extension=zip
extension=intl
extension=exif

; PostgreSQL
extension=pgsql
extension=pdo_pgsql

; SQLite
extension=sqlite3
extension=pdo_sqlite
